site_name: juxt
site_description: Fast desktop tool for navigating N-dimensional hypercubes of plots
site_url: https://juxt.readthedocs.io
repo_url: https://github.com/ColinMoldenhauer/juxt
repo_name: ColinMoldenhauer/juxt

docs_dir: docs

nav:
  - Home: index.md
  - Installation: installation.md
  - Configuration: configuration.md
  - Navigation: navigation.md
  - Remote (SSH): remote.md

theme:
  name: material
  logo: assets/logo_transparent.png
  favicon: assets/logo_transparent.png
  palette:
    scheme: slate
    primary: teal

plugins:
  - search
  - include-markdown
